apiVersion: v2
name: konfigure-operator
version: 1.0.2
appVersion: 1.0.2
home: https://github.com/giantswarm/konfigure-operator
description: A Helm chart for the konfigure-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'false'
  io.giantswarm.application.restrictions.namespace-singleton: 'true'
  io.giantswarm.application.team: honeybadger
